### ISSUE TITLE
Xposed error log 

### ISSUE THREAD

**Issue by terrorist96** [kmark/XHangouts#15]
01-08 13:18:16.880 E/Xposed  (  952): java.lang.IllegalArgumentException: Attempt to launch content provider before system ready
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:9635)
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9820)
01-08 13:18:16.880 E/Xposed  (  952):   at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
01-08 13:18:16.880 E/Xposed  (  952):   at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
01-08 13:18:16.880 E/Xposed  (  952):   at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
01-08 13:18:16.880 E/Xposed  (  952):   at android.content.ContentResolver.query(ContentResolver.java:475)
01-08 13:18:16.880 E/Xposed  (  952):   at android.content.ContentResolver.query(ContentResolver.java:434)
01-08 13:18:16.880 E/Xposed  (  952):   at com.versobit.kmark.xhangouts.Config.reload(Config.java:93)
01-08 13:18:16.880 E/Xposed  (  952):   at com.versobit.kmark.xhangouts.Config.reload(Config.java:83)
01-08 13:18:16.880 E/Xposed  (  952):   at com.versobit.kmark.xhangouts.XHangouts.handleInitPackageResources(XHangouts.java:165)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(IXposedHookInitPackageResources.java:20)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.callbacks.XC_InitPackageResources.call(XC_InitPackageResources.java:28)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:351)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:689)
01-08 13:18:16.880 E/Xposed  (  952):   at android.app.ResourcesManager.getTopLevelResources(<Xposed>)
01-08 13:18:16.880 E/Xposed  (  952):   at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1701)
01-08 13:18:16.880 E/Xposed  (  952):   at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1032)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:675)
01-08 13:18:16.880 E/Xposed  (  952):   at android.app.ApplicationPackageManager.getResourcesForApplication(<Xposed>)
01-08 13:18:16.880 E/Xposed  (  952):   at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:1286)
01-08 13:18:16.880 E/Xposed  (  952):   at android.content.pm.ComponentInfo.loadLabel(ComponentInfo.java:85)
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.policy.ShortcutManager.loadShortcuts(ShortcutManager.java:148)
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.policy.ShortcutManager.<init>(ShortcutManager.java:57)
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.policy.PhoneWindowManager.init(PhoneWindowManager.java:1383)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
01-08 13:18:16.880 E/Xposed  (  952):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:675)
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.policy.PhoneWindowManager.init(<Xposed>)
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.wm.WindowManagerService$4.run(WindowManagerService.java:887)
01-08 13:18:16.880 E/Xposed  (  952):   at android.os.Handler$BlockingRunnable.run(Handler.java:759)
01-08 13:18:16.880 E/Xposed  (  952):   at android.os.Handler.handleCallback(Handler.java:739)
01-08 13:18:16.880 E/Xposed  (  952):   at android.os.Handler.dispatchMessage(Handler.java:95)
01-08 13:18:16.880 E/Xposed  (  952):   at android.os.Looper.loop(Looper.java:148)
01-08 13:18:16.880 E/Xposed  (  952):   at android.os.HandlerThread.run(HandlerThread.java:61)
01-08 13:18:16.880 E/Xposed  (  952):   at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by blackbox87** [comment]
I can't seem to replicate this issue on my Android 5.1.1 phone or my much older Android 4.1.1 phone.

What is your device and what version of Android is it using?

**Comment by kmark** [comment]
Hi, thanks for the bug report. Can you please provide additional information such as: How to replicate this error, Android version (including ROM), Hangouts version, XHangouts version, and any other potentially relevant information that comes to mind.

**Comment by kirmandi** [comment]
getting the same exception after updating to new v2.3 on Marshmallow 6.0.1 (Nexus 5X)
however it is only on boot when the handleInitPackageResources is called, thus it suggest (same as the exception message itself) that contentresolver is not able to access the apps content config this early

nonetheless, xhangouts works fine!
thus it seems reload of config is not even necessary here and might be skipped ?!

**Comment by kmark** [comment]
Thanks for the report. It's looking like we'll need to just remove the configuration reload in the handleInitPackageResources altogether. It didn't seem to work on Jelly Bean but it worked in Lollipop but now it's broken again on Marshmallow. :sweat:

**Comment by kmark** [comment]
Please let me know if this fixes this particular issue (hopefully without breaking anything else): https://drive.google.com/file/d/0BxdUVoV7LNLkcUxtVzhQSHRxY1E/view?usp=sharing

**Comment by kirmandi** [comment]
no exception for me anymore and still working fine ;)

**Comment by kmark** [comment]
Great, thanks for the feedback!

**Comment by terrorist96** [comment]
Fixed for me too with the new update in the repo. Outdated, but yes, I have 6.0.1 on N6p. Thanks!

**Comment by kmark** [comment]
Thanks for testing. This patch was included in the latest release.
