### ISSUE TITLE
Hide the row of "Add [blank]" buttons on keyboard typed.

### ISSUE THREAD

**Issue by wardellbagby** [kmark/XHangouts#17]
I'm referring to the buttons that appear in a chat just above the keyboard, 
![these buttons here](https://cloud.githubusercontent.com/assets/7834478/12267292/04e5789a-b90d-11e5-8291-f203e49f19dd.png). It would be nice if they could be hidden when I'm typing on the keyboard. I've _forever_ accidentally pressing them.

**Comment by kmark** [comment]
As of v2.8 these buttons can be toggled on demand!

Ref: https://github.com/kmark/XHangouts/commit/f90547ed372ec8cd39cd624bdbbf8313ef5f19d2

**Comment by wardellbagby** [comment]
YOU BEAUTIFUL PERSON!
