### ISSUE TITLE
Changing colour changes colour of sent speech bubbles

### ISSUE THREAD

**Issue by KiitoX** [kmark/XHangouts#2]
In not sure if that's possible but that would be awesome.

**Comment by kmark** [comment]
Some work is being done on this by @blackbox87! [See this post on XDA.](http://forum.xda-developers.com/showpost.php?p=64567652&postcount=602)

**Comment by kmark** [comment]
This is now available in XHangouts v2.3 (7d42a428128617def00e24d29ea05c752ab16cf1)
