### ISSUE TITLE
Disable version mismatch error? 

### ISSUE THREAD

**Issue by shikaku2** [kmark/XHangouts#20]
Sometimes it works fine even though hangouts updated. I would disable the module if it didn't. I just want the option to disable it either in options or possibly "until next hangouts update"

**Comment by ghost** [comment]
Minor updates (e.g. 13.0.133066434 to 13.0.134811930) will work but major updates (e.g. 13.0.134811930 to 14.0.136618992) never work.

When you install an unsupported version of Hangouts some of the theme options might still appear to work, but it's actually very broken and will be flooding your Xposed log with errors. That's not something you'd want to ignore as it could cause your battery to drain.

**Comment by kmark** [comment]
@blackbox87 is correct. Installing an unsupported version of Hangouts can have a many unforeseen consequences. If you would only like the design changes or would like to disable the dialog entirely you can always compile the module yourself from source with the features you do not need removed. While the design changes are much more version independent than the other features it is not _completely_ version independent and as such the dialog would still apply there.
