### ISSUE TITLE
Can conversation merging be pulled off from this app?

### ISSUE THREAD

**Issue by wartickler** [kmark/XHangouts#22]
We used to be able to merge hangouts convo's. Yeah Google removed the ability but is there something you can do about that?

**Comment by ghost** [comment]
@wartickler If you use [Hangouts 17.0.148298972](http://www.apkmirror.com/apk/google-inc/hangouts/hangouts-17-0-148298972-release/) with [XHangouts 2.15](https://github.com/kmark/XHangouts/releases/tag/v2.15) then merged conversations will work perfectly. You won't be nagged about SMS support ending either.

**Comment by kmark** [comment]
Once the Hangouts developers strip out the SMS handling code there isn't anything we can do. The best option is to continue using an old release of Hangouts as @blackbox87 suggested with the appropriate release of XHangouts. Eventually Google will deprecate the APIs used by Hangouts 17 which will cause it to stop working. And then SMS on Hangouts will be truly dead barring some monumental reverse engineering effort to restore it.
